### ISSUE TITLE
support VS2022

### ISSUE THREAD

**Issue by MeirAtWork** [Nesviatypaskha/VsConsoleOutput#3]
hi
thanks for the extension.
however I couldn't use since it won't get installed on VS2022.
would be glad to use it

**Comment by Nesviatypaskha** [comment]
Could you please provide more information? The current version support vs2022, but you couldn't install it?

**Comment by MeirAtWork** [comment]
after the installation - I don't see it in the Extensions dialog in the Installed tab

**Comment by Nesviatypaskha** [comment]
![image](https://user-images.githubusercontent.com/19672718/202446861-e05e6ed4-4f02-4b82-9ad6-580f35d59d3b.png)
Something like this?
Please try to find the extension and remove it manually 
https://stackoverflow.com/questions/22444799/how-to-uninstall-vsix-visual-studio-extensions
and then try to install it as usual

**Comment by MeirAtWork** [comment]
weird but after several restarts I can see it now...
anyway, I have created a simple console app and run it but can't see the output in the Output pane
![image](https://user-images.githubusercontent.com/58551103/202447757-5bf11a1b-f5c2-4003-9cae-2e9ce64b7338.png)

**Comment by Nesviatypaskha** [comment]
please try a bigger application. There are some "hucks" used and this one-line application is hard to sync debug start and do some internal manipulations with debug session and tracepoints, You could calculate a simple example and add tracepoint in the first lines of the application. VS2022 version has big changes and it is hard to sync all debug events

**Comment by MeirAtWork** [comment]
cool thanks!
